# Tabu search scheduler

from scheduling.base_scheduler import BaseScheduler
from scheduling.vrptw_model import VRPTWSolution, Route
from environment.environment import VRPTWEnvironment
from .hyper_params import HyperParams
import random
from collections import deque
from copy import deepcopy
from .list_rules import rule_spt, rule_edd, rule_st, rule_ocr
from metrics.metrics import compute_solution_cost
import numpy as np

class InitialSolution:
    def __init__(self, env: VRPTWEnvironment, num_solutions: int = 5):
        """
        Generates a pool of initial solutions for tabu search using predefined rules.
        """
        self.env = env
        self.num_solutions = num_solutions
        self.solutions = self._generate_initial_solutions()

    @staticmethod
    def solution_exists(new_solution: VRPTWSolution, solutions: list) -> bool:
        """
        Checks whether a solution is already present in a list of solutions.
        """
        for sol in solutions:
            if new_solution.dict() == sol.dict():
                return True
        return False

    def _generate_initial_solutions(self):
        """
        Generates a set of initial solutions using the predefined rules.
        """
        solutions = []
        rules = [rule_spt, rule_edd, rule_st, rule_ocr]

        # Generate solutions based on each rule at least once
        for rule in rules:
            solution = rule(self.env)
            if not self.solution_exists(solution, solutions):  # Add only if it is unique
                solutions.append(solution)

        # Generate additional random solutions
        customers_ids = [c.id for c in self.env.customers]
        while len(solutions) < self.num_solutions:
            np.random.shuffle(customers_ids)
            route = Route(vehicle_id=0, sequence_of_customers=customers_ids[:])
            new_solution = VRPTWSolution(routes=[route])
            if not self.solution_exists(new_solution, solutions):  # Check uniqueness
                solutions.append(new_solution)

        return solutions

    def get_random_solution(self) -> VRPTWSolution:
        """
        Returns a random initial solution among the generated ones.
        """
        return deepcopy(np.random.choice(self.solutions))


class Scheduler(BaseScheduler):
    def __init__(self, hyperparams: HyperParams):
        super().__init__(hyperparams)
        self.tabu_list = deque(maxlen=self.hyperparams.tabu_list_size)

    def run(self, env: VRPTWEnvironment, initial_solutions: list = []) -> VRPTWSolution:
        """
        Runs tabu search and returns the best solution found.
        If `initial_solutions` is provided, a random solution is chosen among them.
        If `initial_solutions` is empty, a solution is generated by `rule_ocr` by default.
        """
        if not initial_solutions:
            # Generate a pool of solutions if none is provided
            initial_solutions = InitialSolution(env).solutions
        else:
            # Remove identical solutions if the user provides some
            unique_solutions = []
            for sol in initial_solutions:
                if not InitialSolution.solution_exists(sol, unique_solutions):
                    unique_solutions.append(sol)
            initial_solutions = unique_solutions

        if not initial_solutions:  # If still no solution was generated
            initial_solutions = [rule_ocr(env)]  # Use OCR by default

        # Choose a random initial solution
        current_solution = deepcopy(np.random.choice(initial_solutions))
        best_solution = deepcopy(current_solution)
        best_cost = self.cost(env, best_solution)
        best_iter = 0

        iteration = 0
        while iteration - best_iter < self.hyperparams.max_iterations:
            iteration += 1
            neighborhood = self.neighborhood(current_solution)

            admissible_neighbors = []
            for neighbor in neighborhood:
                if self.is_solution_feasible(env, neighbor) and (neighbor not in self.tabu_list or self.cost(env, neighbor) < best_cost):
                    admissible_neighbors.append(neighbor)

            if not admissible_neighbors:
                break

            next_solution = min(admissible_neighbors, key=lambda sol: self.cost(env, sol))
            next_cost = self.cost(env, next_solution)

            self.tabu_list.append(next_solution)
            current_solution = next_solution

            if next_cost < best_cost:
                best_solution = deepcopy(next_solution)
                best_cost = next_cost
                best_iter = iteration

        return best_solution

    def neighborhood(self, solution: VRPTWSolution) -> list:
        neighbors = []
        if len(solution.routes) < 2:
            # Inter-route swap impossible with a single route: no neighbors,
            # run() then stops cleanly on its own guard.
            return neighbors
        for _ in range(self.hyperparams.neighborhood_size):
            neighbor = deepcopy(solution)
            route1, route2 = random.sample(neighbor.routes, 2)

            if not route1.sequence_of_customers or not route2.sequence_of_customers:
                continue

            idx1 = random.randint(0, len(route1.sequence_of_customers) - 1)
            idx2 = random.randint(0, len(route2.sequence_of_customers) - 1)

            route1.sequence_of_customers[idx1], route2.sequence_of_customers[idx2] = \
                route2.sequence_of_customers[idx2], route1.sequence_of_customers[idx1]

            neighbors.append(neighbor)
        return neighbors

    def cost(self, env: VRPTWEnvironment, solution: VRPTWSolution) -> float:
        return compute_solution_cost(env, solution)

    def is_solution_feasible(self, env: VRPTWEnvironment, solution: VRPTWSolution) -> bool:
        for route in solution.routes:
            demande_totale = 0
            for cid in route.sequence_of_customers:
                c = next((x for x in env.customers if x.id == cid), None)
                if c is None:
                    return False
                demande_totale += c.q
            if demande_totale > env.vehicle_capacity:
                return False
        return True
